### ISSUE TITLE
objective function 

### ISSUE THREAD

**Issue by Mostafa494** [kamal0013/PowNet#2]
Dear Sir,
Good Afternoon,
Thank you for your efforts in  POWNET model.

I am now working with the model to extract different results, my question related to the objective function, how could I extract the values of the objective function to compare it with different models, I will work for 24 hours planning horizon.

Regards

**Comment by kamal0013** [comment]
Thank you for the question. The objective function is actually the hourly production costs. Please, check [this example script](https://github.com/kamal0013/PowNet/blob/master/Model_withdata/analysis_genmix_cost_emi.ipynb) to estimate production costs at hourly and annual scales.

**Comment by Mostafa494** [comment]
Dear Dr. kamal
Thank you very much for your help.
I need to make the best use of your experiences in the model:

  *   Could I apply the system on IEEE 118 system?
  *   How can I define the load demand curve in MW not in MWh as I do not have load data for each bus for each hour in the system?

Regards.


Mostafa Hasaneen
Technical Studies Engineer
Energy Efficiency & Climate Change Department (EEACC)
The Egyptian Ministry of Electricity & Renewable Energy

________________________________

**Comment by kamal0013** [comment]
Here are my answers to the questions:

1) I am not sure but I would suggest to check with the functionalities of the model [here](https://openresearchsoftware.metajnl.com/articles/10.5334/jors.302/).
2) The hourly data are in MW, which can be obtained by disaggregating peak demand with a 24-hourly profile.
